### ISSUE TITLE
How to handle tools (not imported) that end up being reported as "unused" dependencies

### ISSUE THREAD

**Issue by jherland** [tweag/FawltyDeps#117]
From https://github.com/tweag/FawltyDeps/pull/112#discussion_r1097701997:
> Rather I think this is a (separate) issue with FD: When calculating/presenting "unused" dependencies, we should consider ignoring/skipping common tools that are typically declared as dependencies but seldom imported. Examples, just from our own project config:
> - black
> - isort
> - codespell
> - mypy
> - nox
> - pylint
> - pytest
> - fawltydeps 🎉 
>
> Maybe we could try to be smarter about it, like looking for tool configurations in pyproject.toml as proof that a tool is actually being used? But I suspect a simple allow-list might be good enough.

More thought is probably needed about how best to solve this, but we will probably want to do something about this fairly soon, as there are enough of these tools that will keep showing up as "unused dependencies"...

**Comment by Nour-Mws** [comment]
Thanks Zhihan! I am not sure about `colorama`. Why would we need to explicitly include it in the `ignore_unused`? If it's only a _dependency of a dependency_ and not a direct dependency, it shouldn't appear in the dependency configuration file to begin with. Or am I missing something?

**Comment by zz1874** [comment]
Oh thanks for spotting this! Actually `colorama` is a direct dependency in the `dev` group of our `pyproject.toml`, I've updated the list to avoid ambiguity.

**Comment by jherland** [comment]
If we're hardcoding a list of tools that FawltyDeps should `ignore_unused` by default, I think it's very important that it covers as many commonly used tools as possible. This is something that our PyPI experiment should help uncover.

The above is a good starting point, but we should not believe that we're anywhere near finished curating this list... 😅

**Comment by Nour-Mws** [comment]
Attempting to complete the list:
```python
[
    "autopep8",  # Automatic PEP 8 formatting
    "mccabe", # complexity plugin for flake8
    "pre-commit",  # Pre-commit hooks
    "pyformat", # Formatting
    "pytest-cov",  # Coverage plugin for pytest
    "pytest-mock",  # Mocking plugin for pytest
    "pytest-xdist",  # Parallel test execution
    "bandit",  # Security static analysis
    "sphinx",  # Documentation generation
    "recommonmark",  # Markdown support for Sphinx
    "sphinx-rtd-theme",  # Theme for Sphinx
    "pydocstyle",  # Docstring style checking
    "pyflakes", # Formatting
    "rope",  # Refactoring
    "ruff", # Linting in Rust
    "twine",  # Package publishing
    "unify", # unifying quote styles
    "yapf",  # Yet another code formatting option 
]
```

I think it makes to also split those into their respective groups (formatting, linting, security, documentation, etc.. )

**Comment by jherland** [comment]
Thanks for digging into this @Nour-Mws. Note that I'm happy to ship an incomplete list in the initial version of this, as long as we are prepared to add more tools that people suggest.

I'm not familiar with most of the tools in the above list. Most of them seem like tools you'd run from the command-line, but I'm not sure about the `pytest-*` packages?

Should we have a different mechanism for `pytest-*` packages, maybe something more similar to how we handle type stubs?

**Comment by Nour-Mws** [comment]
> I'm not sure about the pytest-* packages?
> Should we have a different mechanism for pytest-* packages, maybe something more similar to how we handle type stubs?

I agree. It makes more sense not to include them here.

**Comment by zz1874** [comment]
Thanks @Nour-Mws :+1:  ! I've updated the list with your inputs (and also excluded pytest-* packages).

**Comment by jherland** [comment]
Copying [my comment from the PR](https://github.com/tweag/FawltyDeps/pull/365#discussion_r1324897753), as it probably rather belongs in this dicussion:

> In general, do we want to consider a more general solution to these categories of plugin packages? Maybe allowing simple globs like pytest-* and sphinx-* in this set? (although this will add complexity to our matching algorithm in fawltydeps/check.py).
> 
> But I'm also very happy to leave this as-is for now. We can always reconsider later if/when we see that more of these packages need to be added.
