### ISSUE TITLE
Allow multiple `--code` and `--deps` options on the command line

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#156]
Quoting @jherland from https://github.com/tweag/FawltyDeps/pull/151#discussion_r1107385503:
> Right now, you can only pass --code and --deps once, and they only take a single Path argument. It probably makes sense to allow multiple --code and --deps options on the command line, and the types here should be adjusted accordingly.

**Comment by jherland** [comment]
Time to close this now, @mknorps?

**Comment by mknorps** [comment]
All done.
