### ISSUE TITLE
Create a GitHub Action to run fawltydeps

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/FawltyDeps#170]
Make a GitHub Action so adding FawltyDeps to a CI on GitHub Actions is a one-liner in the YAML file.

Incorporate getting this published in GitHub Marketplace as contemplated in #332

**Comment by jherland** [comment]
As @vreuter suggest in #332, the GitHub Action should of course be published in the GitHub Marketplace too.

**Comment by obscurerichard** [comment]
I'm happy to take this on.

**Comment by obscurerichard** [comment]
The first cut at this is in https://github.com/tweag/FawltyDeps-action - I made it a separate repo following GitHub's guidelines in [choosing a location for your action](https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action).

**Comment by jherland** [comment]
> The first cut at this is in https://github.com/tweag/FawltyDeps-action - I made it a separate repo following GitHub's guidelines in [choosing a location for your action](https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action).

Looks really good! 🎉

I found a couple of minor things while reviewing it: https://github.com/tweag/FawltyDeps-action/pull/3

**Comment by GuillaumeDesforges** [comment]
The GitHub action is there, I'll mark as done. Thanks a lot @obscurerichard !
