### ISSUE TITLE
When requirements.txt contain a line starting with a dot, FawltyDeps crashes

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#200]
**Describe the bug**
When a `requirement.txt` file contains a line starting with a dot fawltydeps crashes.:

```
tests/test_sample_projects.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fawltydeps/main.py:102: in create
    ret.declared_deps = list(
fawltydeps/extract_declared_dependencies.py:385: in extract_declared_dependencies
    yield from choice_and_parser[1].execute(
fawltydeps/extract_declared_dependencies.py:88: in parse_requirements_contents
    yield parse_one(" ".join(pre_opt_words))
fawltydeps/extract_declared_dependencies.py:54: in parse_one_req
    req = Requirement.parse(req_text)
../../.cache/pypoetry/virtualenvs/fawltydeps-LjqbB_o--py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3145: in parse
    (req,) = parse_requirements(s)
../../.cache/pypoetry/virtualenvs/fawltydeps-LjqbB_o--py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3104: in __init__
    super(Requirement, self).__init__(requirement_string)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'Requirement' object has no attribute 'name'") raised in repr()] Requirement object at 0x7f9f4f943160>, requirement_string = '.'

    def __init__(self, requirement_string: str) -> None:
        try:
            parsed = parse_requirement(requirement_string)
        except ParserSyntaxError as e:
>           raise InvalidRequirement(str(e)) from e
E           pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier
E               .
E               ^

../../.cache/pypoetry/virtualenvs/fawltydeps-LjqbB_o--py3.10/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py:37: InvalidRequirement

```

**To Reproduce**
Run `fawltydeps` in a project with `requirements.txt` containing:
```
. # for running tests
```

**Expected behavior**
Requirement parser parses [requirements specifiers](https://pip.pypa.io/en/stable/reference/requirement-specifiers/#requirement-specifiers) only and debug-prints lines not containing valid requirements.

**Additional context**

According to [requirement file specification](https://pip.pypa.io/en/stable/reference/requirements-file-format/#structure) following forms are supported:

- `[[--option]...]`
- `<requirement specifier>`
- `<archive url/path>`
- `[-e] <local project path>`
- `[-e] <vcs project url>`

Currently, FawltyDeps catches errors when running `parse_one` function, but only if the error is of type `ValueError`. Here, a line starting with a dot made it to the requirements parser and return a different type of error: `InvalidRequirement`

**Proposed solutions**
1. A patch: add encountered error to the list of exceptions that do not obstruct the program flow
2. General: parse requirements.txt as would have pip.

**Comment by jherland** [comment]
Fixed properly via #227
