### ISSUE TITLE
Exclude directories from analysis

### ISSUE THREAD

**Issue by colindean** [tweag/FawltyDeps#226]
**Is your feature request related to a problem? Please describe.**

When I tried to run fawltydeps for the first time, it caught some stuff in my project's `dist` and `build` directories. E.g., `dist` contains a requirements.txt generated from my Poetry config. 

**Describe the solution you'd like**

These directories could be ignored entirely, likely by default but also by configuration.

**Describe alternatives you've considered**

I could run `make clean` to delete these directories before running fawltydeps, but that'd cost extra time later on my workstation. It'd also necessitate running fawltydeps in CI before anything is generated.

**Comment by jherland** [comment]
Thanks for reporting!

I'm wondering if it would be "safe" to always ignore `dist/` and `build/` or if there cases where that would backfire. Maybe safer to take our ignore list from some other source, like `.gitignore`. Would that work in your case?

For now I added this issue to our roadmap (#195).

**Comment by colindean** [comment]
I think it would be safe to use the .gitignore in this case. Thanks for considering this!

**Comment by jherland** [comment]
Note to selves: When we get around to implementing a better mechanism for ignoring files, please take https://github.com/tweag/FawltyDeps/pull/326#discussion_r1259238169 into consideration; in particular: consider if there are cases where the search for code/deps/pyenv sources _differ_ in what paths should be ignored.

For example: it might make sense for code and deps to ignore hidden (dot) dirs, while the pyenv search _should_ descend into these dirs?

**Comment by md384** [comment]
I second this issues and would like to configuration argument that would accept globs (or just simple paths) to ignore to allow a little more flexibility.

**Comment by dorranh** [comment]
+1 for this feature. I've encountered the same issue when running FawltyDeps in a project which had a quick, ad-hov virtual environment created in the project directory for experimentation purposes.

**Comment by jherland** [comment]
With the [v0.15.0 release](https://github.com/tweag/FawltyDeps/releases/tag/v0.15.0), we now support `--exclude` to ignore files and directories. For now, `--exclude` defaults to the `.*` pattern, meaning that "hidden" files/directories are excluded by default.

We don't (yet) exclude `build/` and `dist/` by default, so you'd have to specify `--exclude build/ dist/` on the command-line (or `exclude = ["build/", "dist/"]` in the FawltyDeps section of your `pyproject.toml`)

I'm currently working on a `--exclude-from` option which will allow FawltyDeps to read exclude patterns from a file (like `--exclude-from .gitignore`), but with the basic `--exclude` option there I think we can close this issue. Feel free to reopen if I've overlooked something.
