### ISSUE TITLE
Add tests for `TemporaryPipInstallResolver`

### ISSUE THREAD

**Issue by jherland** [tweag/FawltyDeps#277]
One thing I noticed in rereading the changes is that there are no tests for `TemporaryPipInstallResolver`. You may consider adding it in the follow-up PR, or just create some dummy TODO test in `test_packages.py`, so it does not skip our attention. This can also be a good first issue :)

_Originally posted by @mknorps in https://github.com/tweag/FawltyDeps/issues/268#issuecomment-1486458409_

**Comment by jherland** [comment]
Partially fixed by #323 I believe, as well as #297? Do we need more tests here?

**Comment by mknorps** [comment]
No, I think we are good now, thank you :)
