### ISSUE TITLE
Support running with python -m

### ISSUE THREAD

**Issue by pawamoy** [tweag/FawltyDeps#309]
**Is your feature request related to a problem? Please describe.**
I wanted to debug #307 by actually installing FawltyDeps alongside my project's dependencies instead of isolating it with pipx.
So I ran `python3.9 -m pip install fawltydeps -t __pypackages__/3.9/lib`, and then wanted to run it with `python3.9 -m pip install fawltydeps -t __pypackages__/3.9/lib`, but got the following error message: 

```
/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.15/bin/python3.9: No module named fawltydeps.__main__; 'fawltydeps' is a package and cannot be directly executed
```

Indeed, looking at the code, I see that you don't have a `__main__.py` module.

**Describe the solution you'd like**
Add a `__main__.py` module to the project so that users can run it with `python -m` rather than relying on the shell entrypoint.
This also makes it possible to configure debug sessions in VSCode and others IDE by selecting it as a "module" (instead of current file of executable path).

**Describe alternatives you've considered**
By looking at your `pyproject.toml`, I see that I can use `python -m fawltydeps.main` instead. This is however not easily discoverable.

**Additional context**
Here is my typical `__main__.py` contents:

```python
"""Entry-point module, in case you use `python -m {{ python_package_import_name }}`.

Why does this file exist, and why `__main__`? For more info, read:

- https://www.python.org/dev/peps/pep-0338/
- https://docs.python.org/3/using/cmdline.html#cmdoption-m
"""

import sys

from {{ python_package_import_name }}.cli import main

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
```

**Comment by jherland** [comment]
I created #311 to fix this. Thanks for submitting!
