### ISSUE TITLE
Not supporting PEP-517 and new python build based packaging

### ISSUE THREAD

**Issue by ssbarnea** [tweag/FawltyDeps#347]
It seems that FawltyDeps is unable to correctly detect dependencies from modern projects that are using `build` for packaging, and is missing to spot them.

Example: https://github.com/ansible/ansible-lint/blob/main/pyproject.toml#L12 which is using setuptools-scm with dynamic dependencies as build backend. In this case none of the correctly declared dependencies is detected and the tool reports all dependencies as undeclared, which is not true.

**Comment by jherland** [comment]
Thanks for reporting! We'll look into this as soon as time permits.
