### ISSUE TITLE
Support pydantic v2

### ISSUE THREAD

**Issue by gbdlin** [tweag/FawltyDeps#360]
**Describe the bug**
Right now FawltyDeps requires pydantic v1, which  conflicts with projects using pydantic v2. 

**To Reproduce**
1. create a project that requires pydantic v2 (for example 2.3.0)
2. Add FawltyDeps for the project
3. Observe dependency conflict resolution or errors thrown either by the project or by Fawlty deps due to wrong pydantic version being installed

**Expected behavior**
FawltyDeps should support both v1 and v2 versions of Pydantic, or at some point, fully migrate to v2.

Alternatively, FalwltyDeps can have pydantic vendored, so it doesn't conflict with any project it is used in.

**Environment**
 - OS name + version: Any
 - Version of the code: v0.13.0

**Additional context**
Pydantic v2 was released a while ago and is already popular as it introduces a performance boost and a lot of new features.

**Comment by Nour-Mws** [comment]
Hi @gbdlin, thanks for reporting! We'll look into this and let you know.

**Comment by jherland** [comment]
https://docs.pydantic.dev/latest/migration/ will be helpful while completing this.

**Comment by Nour-Mws** [comment]
Until this is sorted out, @gbdlin, can you tell us more on how you use FawltyDeps?

If it's purely used to check dependencies (in CI for example), it's possible to run it in its own virtual environment. The last release (0.13.0) supports a wide range of ways to resolve your project's dependencies without necessarily needing FawltyDeps to be installed in the same environment as your project.

You can, for example, point FawltyDeps at the venv used in your project with `fawltydeps --pyenv /path/to/project/venv`.
Or better yet, if the venv is under your project's directory, FawltyDeps should be able to automatically detect virtual environments (in linux, we don't yet support automatic discovery in windows).
To see all the ways you have available to you for resolving dependencies, please check the documentation on [resolving dependencies](https://github.com/tweag/FawltyDeps#resolving-dependencies).

**Comment by gbdlin** [comment]
Unfortunately, running it outside the project env would require a major refactor of project's dockerfile an CI.
