### ISSUE TITLE
Detect conditional imports in Python modules

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#377]
Write code to parse Python source files (reuse code from core FD) and Identify conditional imports using AST or regular expressions:
```python
try:
    import foo
except ImportError:
    pass
```

**Comment by mknorps** [comment]
Done in https://github.com/tweag/FawltyDeps/commit/e8943b1d15019d26b0846127cacddd4e09116750#diff-c1f304ee58f5ba0ccf46275f841e6bf8a35c3e0cde20207d696ef4788d73b345
