### ISSUE TITLE
Identify dynamic imports in Python modules

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#379]
Examples:
```python
try:
    module = importlib.import_module("foo")
except ImportError:
    pass
```
or
```python
module = importlib.import_module("foo")
```
or
```python
pytest.importorskip("foo")
```

**Comment by mknorps** [comment]
Please mark `importorskip` differently, as this is important only for tests and not running the program.

**Comment by mknorps** [comment]
First implemented in https://github.com/tweag/FawltyDeps/commit/520496e0610d081a5ded81e91754b4a51315a350 with addition of `importorskip` info: https://github.com/tweag/FawltyDeps/commit/e2a6d8e6149d5945475095b64af11fb850d3227d
