### ISSUE TITLE
Parse imports in docstrings in Python source files

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#380]
- look for patterns indicative of docstring tests (e.g., ">>>")
- or use helper functions from 3rd party modules

**Comment by mknorps** [comment]
Done in https://github.com/tweag/FawltyDeps/commit/e2a6d8e6149d5945475095b64af11fb850d3227d

**Comment by mknorps** [comment]
testing detection code on more complex docstring (with `...`)

**Comment by zz1874** [comment]
Done in https://github.com/tweag/FawltyDeps/commit/fa951a31de6789c845cf427fa1aa4b5ef154731a and https://github.com/tweag/FawltyDeps/commit/485b4f1c9cc38ed7874ad93b1c743fd44a4e0e7e.
