### ISSUE TITLE
Identify dependency declaration files in projects

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#381]

**Comment by zz1874** [comment]
Done in https://github.com/tweag/FawltyDeps/commit/0557a2dba3d2c8ee368377dd6ac35c15f27e283f

**Comment by zz1874** [comment]
Made a minimal modification in rendering the dependency declaration files output as per discussion with @mknorps today in https://github.com/tweag/FawltyDeps/commit/7799584695cbdcdbe70b8eaddbe7643947adeac1 :)
