### ISSUE TITLE
Detect code directories in Python projects

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#382]
Some heuristics:
  - Check for project name declarations in `pyproject.toml` or similar files.
  - Search for the presence of standard directories (e.g., `src/`).
  - Determine the directory with the most `.py` files.
  - Determine the directory and code structure from setup.py or pyproject.toml

**Comment by zz1874** [comment]
Done in https://github.com/tweag/FawltyDeps/commit/a83ecd8e18ff569050f37e29224792e9d2c99a2a and https://github.com/tweag/FawltyDeps/commit/344d168218fc46ff96441f8b46fa0325d769105a.
