### ISSUE TITLE
pre-commit hook doesn't run on just staged files

### ISSUE THREAD

**Issue by msabramo** [tweag/FawltyDeps#385]
**Describe the bug**
The pre-commit hook doesn't run on only files that are staged and being committed. The output will flag undeclared dependencies in files that haven't even been `git add`ed.

**To Reproduce**
```shell
git clone https://github.com/msabramo/fawltydeps-demo1
cd fawltydeps-demo1
pre-commit install
cat > main.py
import requests
import pandas
^D
cat > another.py
import sqlite
^D
git add main.py
git status
# Observe that `main.py` is staged and `another.py` is untracked
git commit
```

The output of `git commit` is:
```
$ git commit
FawltyDeps...............................................................Failed
- hook id: check
- exit code: 3

These imports appear to be undeclared dependencies:
- 'pandas' imported at:
    main.py:2
- 'sqlite' imported at:
    another.py:1
```

This is incorrect because it mentions the undeclared dependency in `another.py` which hasn't even been added to the project yet.

**Expected behavior**
It should've only mentioned the undeclared dependency in `main.py`; not in `another.py`, since I'm not committing that. It doesn't even exist in git at all yet, as we've never added it.

**Environment**
 - OS name + version: Mac OS X 12.6.8
 - Version of the code: `main` branch

**Additional context**

**Comment by msabramo** [comment]
#386 is my attempt at fixing this.

**Comment by jherland** [comment]
Thanks for your report! I agree that the pre-commit hook should run FawltyDeps on the staged changes only. We'll look into this as soon as time permits.
