### ISSUE TITLE
Expose information if parsing of setup.py produced warnings

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#403]
As discussed in team meeting on 4th Dec:

FawltyDeps fails to parse many of the setup.py files in the chosen projects.

We want to gather data for further analysis and need to know:
- Existence of setup.py
- If FD throws warnings (if setup.py exists)

**Comment by zz1874** [comment]
Hey @dorranh, this should be closed due to #404. Thanks for the reminder!
