### ISSUE TITLE
Fix test_traverse_project.py on Windows

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#410]
Testing of project traversing uses sample project, which are written following Unix patterns.
Checking if the Python virtual environment is valid on Windows (a5fb06736edf091ec1c657926886d310dda005d2) makes those tests obviously fail (see https://github.com/tweag/FawltyDeps/actions/runs/7410859336/job/20164065658).

To fix this we may create "twin" sample projects which follows Windows virtual environment patterns.

**Comment by jherland** [comment]
Interesting. This raises a policy question of whether we _should_ detect Unix-style virtualenvs on Windows (or Windows-style virtualenvs on Unix). I guess it comes down to whether we expect our users to run FawltyDeps in this kind of situation?

So either:
1. Test Unix-style virtualenvs on Unix only, and Windows-style virtualenvs on Windows only.
2. Test both Unix-style and Windows-style virtualenvs everywhere.

In both cases, we need to add Windows-style virtualenvs to our sample projects. I'm not sure we need to create "twins" of _all_ the sample projects with virtualenvs, but at least one or two to ensure we have sufficient coverage.
