### ISSUE TITLE
Unable to install v0.14.0

### ISSUE THREAD

**Issue by jharrisonSV** [tweag/FawltyDeps#416]
**Describe the bug**
I am unable to install 0.14.0 using pip.

**To Reproduce**

```
pip install fawltydeps==0.14.0
```

Error Output:
![Screenshot 2024-01-19 at 17 05 11](https://github.com/tweag/FawltyDeps/assets/131665043/f348eb6f-d558-4866-a07c-02ec508cf9f9)

**Expected behavior**
Successful installation of fawtlydeps 0.14.0

**Environment**
 - OS name + version: macOS 14.1
 - Version of the code: v0.14.0

**Additional context**
The [PyPI page](https://pypi.org/project/fawltydeps/) says that the latest release is 0.13.3, which is different to the [GitHub releases page](https://github.com/tweag/FawltyDeps/releases)

**Comment by mknorps** [comment]
Thank you very much for reporting this problem!

Please take a look now. The process for publishing packages on PyPI is not yet automated (https://github.com/tweag/FawltyDeps/issues/124) and I forgot the final `poetry publish` command.

Now it should work fine. I hope it will help you in your projects :)

**Comment by jharrisonSV** [comment]
Yes all working now, thanks for the speedy fix and awesome package!
