### ISSUE TITLE
Link to Discord invite yields an Invite Invalid error screen

### ISSUE THREAD

**Issue by obscurerichard** [tweag/FawltyDeps#430]
**Describe the bug**
The badge in the README links to https://discord.com/invite/53XwX7Ft for _Chat_, but that yields **Invite Invalid**
<img width="1004" alt="image" src="https://github.com/tweag/FawltyDeps/assets/341082/8e177e0f-3c6d-455d-a6e9-761ef1f40574">

**To Reproduce**
View the FawltyDeps home page, click the `chat` badge. 

**Expected behavior**
Getting invited to the FawltyDeps Discord

**Environment**
 - MacOS Ventura 13.6.6 (22G630) x86_64
 - Version of the code: [README.md at v0.15.0](https://github.com/tweag/FawltyDeps/blob/v0.15.0/README.md)

**Additional context**
I'd love to get into Discord!

**Comment by mknorps** [comment]
Thank you for reporting that @obscurerichard :bow: 

Please check this one: https://discord.gg/V2d9xpgD4D.
If it works we will update the FawltyDeps documentation.

**Comment by jherland** [comment]
Works for me:

![Screenshot_20240514_125659](https://github.com/tweag/FawltyDeps/assets/547031/762226c2-b354-4452-950c-72bc9c9339df)

**Comment by jherland** [comment]
Fixed by #436
