### ISSUE TITLE
Look into Pylint alternatives 

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#56]
From https://github.com/tweag/FawltyDeps/pull/39#discussion_r1066484063, which was part of a discussion on Pylint not supporting per-directory configuration:

> ```
> [tool.pylint.tests]
> disable = "missing-function-docstring,invalid-name,redefined-outer-name"
> ```
> The .tests on the first line is disregarded (silently), and the disable directive is applied for all modules, not just our test code.
> 
> In fact, it seems that per-directory settings for Pylint [is not supported upstream (and this issues was first reported in 2015)!.](https://github.com/PyCQA/pylint/issues/6180).
>[..]
> [Consider] abandon[ing]/replac[ing] Pylint altogether. We're probably not there yet, but - frankly - it's popped into the back of my mind a couple of times now:
> We're running into a fair amount of issues getting it properly configured.
> Some of the warnings it produces are very opinionated/strict, even when I feel the code in question looks pretty good. Refactoring our code just to make Pylint happy, is something I'd rather not have to do a lot of...
> Pylint seems to have fallen out of favor in recent times compared to other linters. For example, a lot of cookiecutter repos I've looked recently does not include it among their preferred linters. Also, [this blog post](https://inventwithpython.com/blog/2022/11/19/python-linter-comparison-2022-pylint-vs-pyflakes-vs-flake8-vs-autopep8-vs-bandit-vs-prospector-vs-pylama-vs-pyroma-vs-black-vs-mypy-vs-radon-vs-mccabe/) compares a bunch of linters, and Pylint does not come out on top.

**Comment by mknorps** [comment]
We moved to `ruff`. This was implemented by @jherland in a series of PRs: #424, #425, #426.
