### ISSUE TITLE
Look into the `import-requirements` `pylint` plugin

### ISSUE THREAD

**Issue by Nour-Mws** [tweag/FawltyDeps#59]
This is low priority and it isn't clear how relevant the library is. Beyond possibly including this in the related work section of the design doc, It could be useful to also understand how this is added to Pylint.
From https://github.com/tweag/FawltyDeps/pull/47#issuecomment-1378353276:

> It did not came up in the literature research, but it is relevant to an extent. This library checks if an import (the check is done only for last parsed Import and ImportFrom) has a matching installed dependency. This also is a part of pigar for example, and I think we also should support this option later. It will not be useful for CI, but for development environment yes.

https://github.com/WanzenBug/pylint-import-requirements

**Comment by jherland** [comment]
This is not part of what we want FD to in the short-medium term. FD is about checking your imports against your _declared_ deps (`setup.py`, `requirements.txt`, `pyproject.toml`, etc.), **NOT** about checking your imports against your _installed_  deps (i.e. what's in your project's virtualenv).
