### ISSUE TITLE
Sanitize names of imports and dependencies

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#88]
There is an inconsistency in sanitizing dependencies and import names.

When requirements are parsed with the `parse_requirements` function  from `pkg_resources`, the string for `requirement.key` is changed to lower case. We use this value to compare to parsed imports. 
The problem is that imports distinguish letter cases, see example by @jherland:
```
$ echo "print('this is bar')" > bar.py
$ echo "print('THIS IS BAR')" > BAR.py
$ echo "import BAR" > foo.py
$ python3 foo.py 
THIS IS BAR
```

Following @Nour-Mws 's research:

The [Python code style guide](https://peps.python.org/pep-0008/#package-and-module-names) recommends:
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

There seems to be exceptions, e.g. cPickle (which apparently got fixed in Python 3), but this means, as Johan's experiment above showed, that it's still practically possible. https://stackoverflow.com/a/43130807

The problem described above should appear rarely.

To solve it, we need to:
1. Do the research if the problem concerns only  cases (maybe special characters are sanitized as well)
2. Decide and implement a common format for imports and dependencies

**Comment by jherland** [comment]
Closing this, as we have a fair grip on this after merging #193, as well as the deeper analysis on #176 revealing an issue that is not related to the normalization/sanitzation of package/dependency names.
